### ISSUE TITLE
Create git tag and docker image tags

### ISSUE THREAD

**Issue by ebarault** [krezreb/pimp-my-port21#1]
Hi @krezreb , 
could you please create a tag/release on this repo as well as the associated tags at dockerhub level so we can have a stable reference to your work in our codebase?
Thx!

**Comment by krezreb** [comment]
Happy new year!

https://github.com/krezreb/pimp-my-port21/releases/tag/v1.0

**Comment by ebarault** [comment]
hi @krezreb , thanks for the tag!
could you also create a tag on dockerhub on this image ?
https://hub.docker.com/r/jbeeson/proftpd-admin/tags

currently, the tag only propagated to 
https://hub.docker.com/r/jbeeson/proftpd-slim/tags

**Comment by krezreb** [comment]
Sorry about that, it's done now
