### ISSUE TITLE
use proftpd 1.3.6.b

### ISSUE THREAD

**Issue by ebarault** [krezreb/pimp-my-port21#2]
hi @krezreb , 

There's a much more recent release of proftp 1.3.6 : 

![image](https://user-images.githubusercontent.com/12000935/72166913-6dfe1580-33ca-11ea-9c4a-484c1e7ba15c.png)

Would you mind building a 1.3.6b tag using this version ?
required change is here: https://github.com/krezreb/pimp-my-port21/blob/master/Dockerfile-proftpd-alpine-source#L5

**Comment by ebarault** [comment]
@krezreb could you merge https://github.com/krezreb/pimp-my-port21/pull/3 and build the `pre-1.3.6c` tag so we can test ?

**Comment by krezreb** [comment]
merged
FYI also added 1.3.7rc3 tag
